export default {
  GET_TRANSACTIONS_START: 'GET_TRANSACTIONS_START',
  GET_BALANCE_SUCCESS: 'GET_BALANCE_SUCCESS',
//   GET_COSTS_START: 'GET_COSTS_START',
  GET_COSTS_SUCCESS: 'GET_COSTS_SUCCESS',
//   POST_INCOME_START: 'POST_INCOME_START',
  POST_INCOME_SUCCESS: 'POST_INCOME_SUCCESS',
};
