export default {
  FETCH_START: 'FETCH_START',
  GET_BALANCE_SUCCESS: 'GET_BALANCE_SUCCESS',
  GET_COSTS_SUCCESS: 'GET_COSTS_SUCCESS',
  POST_INCOME_SUCCESS: 'POST_INCOME_SUCCESS',
  FETCH_ERROR:"FETCH_ERROR",
  DATE_NOW:"DATE_NOW"
};
